### ISSUE TITLE
Deeply nested infobox

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#264] opened 2019-04-04 11:52 UTC
Topic Spain
https://en.wikipedia.org/wiki/Spain
The text contains wiki markup.

![2019-04-04_1450](https://user-images.githubusercontent.com/435827/55553562-2df65d80-56e9-11e9-928d-47138f732d38.png)

**Comment by spencermountain** [comment] 2019-04-04 21:23
yikes
took a look briefly - 
```
country infobox
   → collapsible list
     → another unnamed infobox
```
likely a dupe of #247 
hopefully that will fix it -
cheers

**Comment by spencermountain** [comment] 2019-04-23 15:15
merging this with #247

**Comment by yanosh-igor** [comment] 2019-10-03 09:36
@spencermountain Hey, unfortunately, it wasn't fixed 
Another example is https://en.wikipedia.org/wiki/Ukraine

![2019-10-03_1234](https://user-images.githubusercontent.com/435827/66115793-3406c180-e5da-11e9-8fd6-d40eb9d2d562.png)

**Comment by spencermountain** [comment] 2019-10-03 13:46
yeah, i've just merged it with #247 it is still open.

**Closed by spencermountain** 2019-10-03 13:46 UTC
Labels: bug
