### ISSUE TITLE
two or more links with the same target or name on the same line breaks HTML link formatting

### ISSUE THREAD

**Issue by waldenn** [spencermountain/wtf_wikipedia#367] opened 2020-05-13 03:41 UTC
[minimal example](https://conze.pt/app/wtf-debug/?outputType=html&text=%5B%5Bfoo%5D%5D%20%5B%5Bfoo%5D%5D%0A%0A%5B%5Bfoo%5D%5D%20%5B%5Bbaz%7Cfoo%5D%5D%0A%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

[wikipedia example](https://en.wikipedia.org/wiki/Super_30) (the first line contains two links to India)

**Comment by spencermountain** [comment] 2020-05-13 12:14
hey waldenn, this looks like a dupe of #300 
thanks

**Closed by spencermountain** 2020-05-13 12:14 UTC

**Comment by waldenn** [comment] 2020-05-13 12:19
Alright. Thanks!
