### ISSUE TITLE
`'''Mr.` in sentence parser

### ISSUE THREAD

**Issue by yanosh-igor** [spencermountain/wtf_wikipedia#215] opened 2018-11-26 11:54 UTC
Hi, sentences that have the word "Mr." wrongly parsed.
Here is an example:
https://en.wikipedia.org/wiki/Mr._Lawrence
First sentence parsed as `Douglas Lawrence Osowski (born January 1, 1969), credited as '''Mr.`
![2018-11-26_1352](https://user-images.githubusercontent.com/435827/49012605-91dca880-f182-11e8-9e8a-0aa58348c236.png)
Insead of:
![2018-11-26_1353](https://user-images.githubusercontent.com/435827/49012655-b9337580-f182-11e8-99d3-cc125374181b.png)

**Comment by niebert** [comment] 2018-11-28 08:14
"." is a sentence separator. Necessary to introduce a blacklist of exeptions. I guess  "e.g. " will also separate sentences in an inappropriate way.

**Comment by MatthewAwesome** [comment] 2018-11-28 16:14
I concur with the blacklisting thing suggestion. However, there are bound to be some exceptions that rear their head on a rolling basis. Thus, in addition, might we be able to employ a natural language processing solutions to test the validity of sentences, identify fragments, and stitch them together as needed?

I've got a mid-december deadline; if this remains unresolved then, I'll think more about it once I'm a bit more free.  

Stay awesome!

**Comment by spencermountain** [comment] 2018-11-28 16:18
hey, sorry for not weighing into this, the issue is not the period, but the punctuation.

[the parser](https://github.com/spencermountain/wtf_wikipedia/blob/master/src/04-sentence/sentence-parser.js) has [a list of abbreviations](https://github.com/spencermountain/wtf_wikipedia/blob/master/src/_data/abbreviations.js), which includes mr, and all the others from the [nlp-compromise](https://github.com/spencermountain/compromise/) sentence tokenizer.

WIll look at this punctuation issue this week.
cheers

**Comment by spencermountain** [comment] 2018-12-04 01:08
this is fixed in `7.0.0` 🤙 
thanks!

**Closed by spencermountain** 2018-12-04 01:08 UTC
Labels: bug

**Comment by spencermountain** [comment] 2018-12-07 19:44
yeah, i like that!
