### ISSUE TITLE
Parsing of <ref group="note"> can fail

### ISSUE THREAD

**Issue by fractalien** [spencermountain/wtf_wikipedia#85] opened 2018-02-28 23:17 UTC
In [London / EN](https://en.wikipedia.org/wiki/London), there is a section `<ref group="note">...</ref>` of which the parser keeps the starting tag and the content.

**Comment by dmh-cs** [comment] 2018-08-06 21:59
My understanding is that in order for this to work without breaking anything, we'll have to drop xml after parsing the citations. But that seems complicated since that is done inside the sections processing section.

**Comment by spencermountain** [comment] 2018-08-07 16:01
yeah, that's correct. we're getting burned by order-of-operations stuff all-over the place.
@fractalien i can't find it, am I missing something?
```js
wtf.fetch('London', 'en', function(err, doc) {
  console.log(doc.plaintext().match('"ref"'));
});
```
cheers

**Comment by spencermountain** [comment] 2018-09-19 14:57
closing until this can be reproduced

**Closed by spencermountain** 2018-09-19 14:57 UTC
Labels: bug

**Comment by niebert** [comment] 2018-09-20 14:55
a workaround for this can be a replacement of REF XML-tags by a kind of text token `___REF_GROUP_note____` and the parser will regard that as ordinary text and it remains even in the plain text as output.  
```xml
<ref group="note">
```
Even in plain text finally the a replacement of citations into "[1]" can be perform without any need to alter `kill_xml()`. Of course it is a hack to generation of an AST tree node for data, that we want to preserve.
Furthermore those type of tokens will not cause any conflict with any other parsing steps. We could replace the underscore by another character wrapping the `ref`-data we want to preserve, as long as it does not creates any conflict with existing syntax of the wiki source.  

If Spencer is Ok with implementing such a workaround and preserve the current order of parsing and killing XML. 
cheers

**Comment by spencermountain** [comment] 2018-09-21 17:29
ah, sorry I misunderstood this issue. I didn't know wikipedia had a special thing for references-as-notes.

yeah, niebert's strategy for doing this a-priori on the string would work. You could also pre-match them, and store offsets somehow. I have been shy about doing these, as we're throwing-around, and changing wikitext all-over the place.

There's no problem parsing these notes, storing them in `doc.references`, and rendering them somehow. Happy to do it.

**Comment by fractalien** [comment] 2019-02-11 20:27
I'm sorry for the late reply – only now got to work on my project again. The tag is still [there](https://en.wikipedia.org/w/index.php?title=London&action=edit), but it's cleanly absent from the sentences' text now. Thanks for whichever other measure fixed it!
